### ISSUE TITLE
[Bug] Kick player | Bug animation

### ISSUE THREAD

**Issue by Sepera-okeq** [elidhan/Simple-Animated-Guns#10]
When trying to somehow interact with the weapon, a kick occurs from the server.

Server: 1.20.1

Log:  

```
[18:57:25] [Server thread/INFO]: Player sepera_okeq joined with a matching carpet client
[18:58:18] [Server thread/WARN]: Failed to handle packet for /78.85.195.126:63557
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bck000$carpet$modifiedRunLoop(MinecraftServer.java:15442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "mod.azure.azurelib.core.animation.RawAnimation.equals(Object)" because the return value of "mod.azure.azurelib.core.animation.AnimationController.getCurrentRawAnimation()" is null
	at net.elidhan.anim_guns.item.GunItem.method_7888(GunItem.java:306) ~[animated_guns-1.2.jar:?]
	at net.minecraft.class_1799.method_7917(class_1799.java:490) ~[server-intermediary.jar:?]
	at net.minecraft.class_1661.method_7381(class_1661.java:256) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
	... 10 more
[18:58:18] [Server thread/INFO]: sepera_okeq lost connection: Internal server error
```

**Comment by elidhan** [comment]
Fixed, had to make some things happen on the client side instead of the server side
